---
- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: start nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: import code using common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req  # import role from common roles with file name app-pre-req.yaml file

- name: copy the frontend config file
  ansible.builtin.template:
    src: frotend.conf.j2
    dest: /etc/nginx/default.d/frotend.conf
  notify:            #it wll search for it in handlers directory
  - restart the nginx


